job1:
  stage: build
  script:
    - git submodule update --recursive --init
    - mkdir build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - ninja
  only:
    - release
