.build:variables:
  variables: &build_variables
    GIT_SUBMODULE_STRATEGY: recursive
    URDE_MACOS_CODESIGN_UID: VMFVV424V2

.build:macos: &macos_definition
  stage: build
  tags:
    - macos
  script:
    - mkdir build
    - cd build
    - >
      cmake
      -GNinja
      -DCMAKE_BUILD_TYPE=RelWithDebInfo
      -DLLVM_ROOT_DIR=/opt/urde-llvm
      -DURDE_DLPACKAGE=urde-$CI_PIPELINE_ID-macos-x86_64-$URDE_VECTOR_ISA
      -DURDE_VECTOR_ISA=$URDE_VECTOR_ISA
      ..
    - ninja urde hecl visigen
    - cd Editor
    - cp -R urde.app $CI_PROJECT_DIR/URDE.app
    - cd $CI_PROJECT_DIR
    - codesign -s $URDE_MACOS_CODESIGN_UID -v --deep URDE.app
  only:
    - release
  artifacts:
    name: "urde-$CI_PIPELINE_ID-macos-x86_64-$URDE_VECTOR_ISA"
    paths:
      - URDE.app/
    expire_in: 1 week

build:macos:sse3:
  <<: *macos_definition
  variables:
    <<: *build_variables
    URDE_VECTOR_ISA: sse3

#build:macos:sse41:
#  <<: *macos_definition
#  variables:
#    <<: *build_variables
#    URDE_VECTOR_ISA: sse41

#build:macos:avx:
#  <<: *macos_definition
#  variables:
#    <<: *build_variables
#    URDE_VECTOR_ISA: avx

#build:macos:avx2:
#  <<: *macos_definition
#  variables:
#    <<: *build_variables
#    URDE_VECTOR_ISA: avx2

deploy:
  stage: deploy
  tags:
    - server
  script:
    - python3 /var/lib/gitlab-runner/deploy_urde.py $CI_PIPELINE_ID
